from __future__ import annotations

SECTOR_MAP: dict[str, str] = {
    # L1
    "BTC/USDT": "L1", "ETH/USDT": "L1", "SOL/USDT": "L1",
    "ADA/USDT": "L1", "AVAX/USDT": "L1", "DOT/USDT": "L1",
    "NEAR/USDT": "L1", "ATOM/USDT": "L1", "APT/USDT": "L1",
    "SUI/USDT": "L1", "SEI/USDT": "L1", "TIA/USDT": "L1",
    "ICP/USDT": "L1", "FTM/USDT": "L1", "ALGO/USDT": "L1",
    "HBAR/USDT": "L1", "TON/USDT": "L1", "TRX/USDT": "L1",
    # DeFi
    "UNI/USDT": "DEFI", "AAVE/USDT": "DEFI", "MKR/USDT": "DEFI",
    "SNX/USDT": "DEFI", "COMP/USDT": "DEFI", "CRV/USDT": "DEFI",
    "SUSHI/USDT": "DEFI", "1INCH/USDT": "DEFI", "DYDX/USDT": "DEFI",
    "LDO/USDT": "DEFI", "RPL/USDT": "DEFI", "PENDLE/USDT": "DEFI", "JUP/USDT": "DEFI",
    # AI
    "FET/USDT": "AI", "RNDR/USDT": "AI", "AGIX/USDT": "AI",
    "OCEAN/USDT": "AI", "TAO/USDT": "AI", "WLD/USDT": "AI",
    "AKT/USDT": "AI", "AR/USDT": "AI",
    # Gaming
    "AXS/USDT": "GAMING", "SAND/USDT": "GAMING", "MANA/USDT": "GAMING",
    "GALA/USDT": "GAMING", "IMX/USDT": "GAMING", "ILV/USDT": "GAMING",
    "RONIN/USDT": "GAMING", "PIXEL/USDT": "GAMING",
    # L2
    "MATIC/USDT": "L2", "OP/USDT": "L2", "ARB/USDT": "L2",
    "STRK/USDT": "L2", "METIS/USDT": "L2", "MANTA/USDT": "L2", "ZK/USDT": "L2",
    # Meme
    "DOGE/USDT": "MEME", "SHIB/USDT": "MEME", "PEPE/USDT": "MEME",
    "BONK/USDT": "MEME", "FLOKI/USDT": "MEME", "WIF/USDT": "MEME",
    # Infrastructure
    "LINK/USDT": "INFRA", "GRT/USDT": "INFRA", "FIL/USDT": "INFRA",
    "THETA/USDT": "INFRA", "PYTH/USDT": "INFRA", "TRB/USDT": "INFRA",
    # Privacy
    "XMR/USDT": "PRIVACY", "ZEC/USDT": "PRIVACY",
    # Exchange
    "BNB/USDT": "EXCHANGE", "CRO/USDT": "EXCHANGE", "OKB/USDT": "EXCHANGE",
}

TOP_COINS = [
    "BTC/USDT", "ETH/USDT", "BNB/USDT", "SOL/USDT", "ADA/USDT",
    "AVAX/USDT", "DOT/USDT", "LINK/USDT", "MATIC/USDT", "NEAR/USDT",
    "ATOM/USDT", "UNI/USDT", "APT/USDT", "OP/USDT", "ARB/USDT",
    "SUI/USDT", "SEI/USDT", "TIA/USDT", "FET/USDT", "RNDR/USDT",
]

MAX_OPEN_TRADES = 15
MAX_EXPOSURE_PCT = 0.85
MAX_SINGLE_PAIR_PCT = 0.20
MAX_SECTOR_PCT = 0.35
MIN_SECTORS = 3
MAX_CORRELATION = 0.85
TIMEFRAMES = ["5m", "15m", "1h", "4h", "1d"]
BASE_TIMEFRAME = "5m"
CANDLES_PER_HOUR = 12
CANDLES_PER_DAY = 288
HEARTBEAT_INTERVAL = 1
MIN_TRADES_FOR_LEARNING = 20
MAX_PARAMETER_DRIFT = 0.50
LEARNING_COOLDOWN_CANDLES = 288
BASE_LEARNING_RATE = 0.01
